# Warmup Exercise

- set the seed to be 765 with numpy
- create a 5*3 numpy array from random numbers between 0 and 1
- multiple the array by 4
- make the array 1 dimensional
- what is the max value
- identify the index for that largest value




In [6]:
pip install numpy

     |████████████████████████████████| 14.5 MB 3.8 MB/s eta 0:00:01     |███████████████████████████▋    | 12.5 MB 3.8 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import random

In [7]:
import numpy as np

In [10]:
np.random.seed(765)

In [11]:
a=np.random.rand(5,3)

In [15]:
a

array([[0.47622943, 0.46378993, 0.29035724],
       [0.94356321, 0.25553297, 0.73366691],
       [0.70950592, 0.89212214, 0.20222305],
       [0.79012439, 0.82681928, 0.68601438],
       [0.1526213 , 0.70779554, 0.05825119]])

In [12]:
a.shape

(5, 3)

In [13]:
a.ndim

2

In [14]:
b=a*(4)
b

array([[1.90491773, 1.85515973, 1.16142896],
       [3.77425284, 1.02213187, 2.93466764],
       [2.83802369, 3.56848857, 0.80889221],
       [3.16049755, 3.30727714, 2.74405751],
       [0.6104852 , 2.83118215, 0.23300477]])

In [16]:
b=b.flatten()
b

array([1.90491773, 1.85515973, 1.16142896, 3.77425284, 1.02213187,
       2.93466764, 2.83802369, 3.56848857, 0.80889221, 3.16049755,
       3.30727714, 2.74405751, 0.6104852 , 2.83118215, 0.23300477])

In [17]:
b.max()

3.774252844888631

In [18]:
b.argmax()

3

# Basic Stats in Python

![](https://www.statology.org/wp-content/uploads/2018/10/normal_dist.png)

In [ ]:
# import scipy to start
import scipy

In [19]:
# installs (reverse order, but to show a flow that is normal, but I don't typically recommend)
!pip install scipy


     |████████████████████████████████| 25.9 MB 10.1 MB/s eta 0:00:01   |█▍                              | 1.1 MB 4.2 MB/s eta 0:00:06


In [20]:
# lets try this again (scipy and numpy)
from scipy import stats


> Let's quickly check our conda environment

# One Sample T-test



> TIP: shit + tab to help get the documentation, tab to get methods

In [22]:
# create a 1d array from a normal dist 0/1
# size = 15
x=np.random.normal(size=15)
x

array([ 1.73800112, -0.09651708, -1.19267086,  0.30879389,  0.10119238,
       -0.40643211, -0.93546968, -0.30523465,  1.64602449,  0.9127755 ,
       -1.49338113,  1.22516148,  1.54364954, -0.75343863,  0.32418097])

In [ ]:
x.shape

In [ ]:
x.std()

In [ ]:
x.mean()

In [23]:
# ttest from scipy
stats.ttest_1samp(x,0)


Ttest_1sampResult(statistic=0.6407598162915835, pvalue=0.5320277337512018)

In [24]:
# try this again - larger sample
# size = 100
y=np.random.normal(size=100)
y

array([ 1.07478786, -1.62849468, -1.36233211,  1.81893749, -0.18140081,
       -0.41307506, -1.04390999, -0.91309722,  0.08779932, -0.09968   ,
       -0.96605826, -0.25268973,  1.02905096, -0.38455586, -0.15936053,
        0.71352571,  0.29788496,  1.0257826 ,  1.02419829,  0.70269132,
        0.53887887,  1.03456033,  0.18994755, -2.26443528,  0.23121966,
       -0.0608769 ,  1.13399519,  2.40473817,  0.13669265, -0.29683122,
       -0.38573267,  0.98403699, -0.99717868, -1.28572328, -1.52848242,
        0.82941257, -0.73792226,  0.5073189 , -2.61758765,  0.17690287,
       -0.25125723, -1.55616262, -0.4002257 , -0.54954596,  0.37089844,
        1.58005908, -0.32550555, -0.86475762, -0.89527254,  0.89871173,
       -0.93085579,  0.30618861,  1.088305  , -0.82927828,  0.34777667,
        0.1424718 , -0.86197291, -0.11961697,  0.72414027, -0.84363413,
       -0.24992957, -0.02891445, -0.01710073, -1.04029303, -1.70390176,
        0.958037  ,  1.68066254, -0.25577116, -1.24894874,  1.39

In [25]:
stats.ttest_1samp(y,0)

Ttest_1sampResult(statistic=-0.7687734585602507, pvalue=0.4438579359190308)

> Makes sense right, as sample size increases from the distribution, pvalue gets larger.  Much less unlikely to be from a different dist

In [26]:
# another but we shift the data to 2/1, size=50
z=np.random.normal(loc=2,scale=1,size=50)

In [27]:
# save out the result to a variable
# result
result=stats.ttest_1samp(z,0)
result

Ttest_1sampResult(statistic=16.240783101130667, pvalue=2.328546282148322e-21)

In [ ]:
# type
type(result)

In [28]:
# parse to list
list(result)

[16.240783101130667, 2.328546282148322e-21]

## Your Turn

In [ ]:
# create an array with mean 85 and standard deviation of 3
# test against a population mean of 91
#size 50

In [29]:
w=np.random.normal(loc=85,scale=3,size=50)

In [30]:
w_test=stats.ttest_1samp(w,91)

In [31]:
w_test

Ttest_1sampResult(statistic=-13.96574625059449, pvalue=1.0425544046060789e-18)

# Two Sample t-test

In [32]:
# lets create two random normal, 100/15, 115/15, size=100
x_1=np.random.normal(100,15,100)
y_1=np.random.normal(115,15,100)

In [34]:
print(x_1.mean())
print(y_1.mean())

99.92201418253546
113.07220694533186


In [ ]:
stats.ttest_ind(x_1,y_1)

> Assumes equal variances.  Review help to set if not.

## Your Turn

In [36]:
# starter code
math = np.genfromtxt('math.txt', delimiter=",")
print(math.shape)
verbal = np.genfromtxt('verbal.txt', delimiter=",")
print(verbal.shape)

(1000,)
(1000,)


In [37]:
# are the means of math and verbal statistically different?
# assume unequal variances
math.mean()

1000.2158496759128

In [38]:
verbal.mean()

1021.9454110965971

In [40]:
stats.ttest_ind(math,verbal,equal_var=False)

Ttest_indResult(statistic=-9.48983093882732, pvalue=7.445646122216737e-21)

> Stepping back, you can see that we can use numpy to save out data.  This is quick for this course, but we can also use pickles.  We will talk about that later.

## pingouin

In [41]:
# install
! pip install pingouin

     |████████████████████████████████| 223 kB 4.3 MB/s eta 0:00:01
     |████████████████████████████████| 9.5 MB 11.2 MB/s eta 0:00:01
     |████████████████████████████████| 11.6 MB 30.6 MB/s eta 0:00:01     |███████████████████████████▉    | 10.1 MB 30.6 MB/s eta 0:00:01
     |████████████████████████████████| 283 kB 33.2 MB/s eta 0:00:01
     |████████████████████████████████| 9.5 MB 37.6 MB/s eta 0:00:01
     |████████████████████████████████| 6.8 MB 57.4 MB/s eta 0:00:01
     |████████████████████████████████| 510 kB 77.0 MB/s eta 0:00:01
     |████████████████████████████████| 2.2 MB 77.7 MB/s eta 0:00:01
     |████████████████████████████████| 88 kB 14.4 MB/s eta 0:00:01
     |████████████████████████████████| 231 kB 61.9 MB/s eta 0:00:01
     |████████████████████████████████| 301 kB 71.2 MB/s eta 0:00:01
     |████████████████████████████████| 720 kB 83.4 MB/s eta 0:00:01
  Created wheel for pingouin: filename=pingouin-0.3.8-py3-none-any.whl size=221688 sha256=8c05053bae862c

> Lots of packages installed for us, inlcluding ones you could use later in the program

In [42]:
import pingouin as pg

In [43]:
# new parameter - correction
pg.ttest(math, verbal, correction=True)

T         dof       tail         p-val             CI95%  \
T-test -9.489831  1713.89445  two-sided  7.445646e-21  [-26.22, -17.24]   

         cohen-d      BF10  power  
T-test  0.424398  5.09e+17    1.0

# Chi-square

In [44]:
## test for indepdence
# example set from here
# 4 sets of rolls of dice, summarized

a1 = [6, 4, 5, 10]
a2 = [8, 5, 3, 3]
a3 = [5, 4, 8, 4]
a4 = [4, 11, 7, 13]
a5 = [5, 8, 7, 6]
a6 = [7, 3, 5, 9]
dice = np.array([a1, a2, a3, a4, a5, a6])

In [45]:
dice

array([[ 6,  4,  5, 10],
       [ 8,  5,  3,  3],
       [ 5,  4,  8,  4],
       [ 4, 11,  7, 13],
       [ 5,  8,  7,  6],
       [ 7,  3,  5,  9]])

In [46]:
stats.chi2_contingency(dice)

(16.490612061288754,
 0.35021521809742745,
 15,
 array([[ 5.83333333,  5.83333333,  5.83333333,  7.5       ],
        [ 4.43333333,  4.43333333,  4.43333333,  5.7       ],
        [ 4.9       ,  4.9       ,  4.9       ,  6.3       ],
        [ 8.16666667,  8.16666667,  8.16666667, 10.5       ],
        [ 6.06666667,  6.06666667,  6.06666667,  7.8       ],
        [ 5.6       ,  5.6       ,  5.6       ,  7.2       ]]))

In [47]:
# another way to unpack the results
stat, p, dof, exp=stats.chi2_contingency(dice)


In [48]:
p

0.35021521809742745

> What just happened?  We can unpack the results  by itemizing the values as variables.  You will see this quite a bit in the scikit learn syntax when doing train/test splits.

![](https://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/Figure3.PNG)

In [49]:
# another example
# https://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData5.html
# by group, yes/no

g1 = [5, 78]
g2 = [21, 63]
data = np.array([g1, g2])
data

array([[ 5, 78],
       [21, 63]])

In [50]:
data.sum(axis=1)


array([83, 84])

> pingouin is looking for a pandas dataframe, a more practical way to collect data and calculate contingency tables

In [51]:
# of course, if you wanted to break this down and calculate by hand, we have seen the necessary tooling to start to calculate counts, relate, etc.
stats.chi2_contingency(data)

(10.038288989094873,
 0.0015331954846715006,
 1,
 array([[12.92215569, 70.07784431],
        [13.07784431, 70.92215569]]))

---

## Your Turn

A manager at a manufacturing plant wants to evaluate if there are quality differences across the workers on three different shifts.  Determine if there are differing levels of quality at the plant.



|      shift           | Perfect | Satisfactory | Defective |
|-----------------|---------|--------------|-----------|
| Morning Shift   | 106     | 124          | 1         |
| Afternoon Shift | 67      | 85           | 1         |
| Night Shift     | 37      | 72           | 3         |

Source: https://online.stat.psu.edu/stat500/lesson/8/8.1

In [52]:
M1=[106,67,37]
A1=[67,85,1]
N1=[37,72,3]
data1=np.array([M1,A1,N1])
data1

array([[106,  67,  37],
       [ 67,  85,   1],
       [ 37,  72,   3]])

In [53]:
stats.chi2_contingency(data1)

(60.18254657892968,
 2.655611649572069e-12,
 4,
 array([[92.84210526, 99.03157895, 18.12631579],
        [67.64210526, 72.15157895, 13.20631579],
        [49.51578947, 52.81684211,  9.66736842]]))