# A very quick intro to sim in python

In [1]:
import numpy as np


In [2]:
x = np.random.rand(5)

In [3]:
x

array([0.85680187, 0.89979378, 0.79691071, 0.0688851 , 0.89520743])

In [5]:
x = np.random.choice(range(10), size=10)

In [6]:
x

array([3, 3, 0, 7, 8, 2, 1, 6, 8, 6])

# Uniform distribution

In [7]:
dice = [1,2,3,4,5,6]

In [8]:
dice

[1, 2, 3, 4, 5, 6]

In [11]:
roll = np.random.choice(dice, size=1)

In [12]:
roll

array([4])

In [13]:
rolls = []
for i in range(10):
    roll = np.random.choice(dice, size=1)
    rolls.append(roll)

In [14]:
rolls

[array([1]),
 array([6]),
 array([3]),
 array([2]),
 array([5]),
 array([5]),
 array([1]),
 array([5]),
 array([4]),
 array([3])]

# Normal distribution

In [19]:
norm = np.random.normal(size=100)

In [20]:
norm

array([-2.22204024, -0.52800817, -0.39178918, -1.65582873,  0.34370982,
        0.00527119, -1.75467596, -0.54731049, -0.50302952, -1.4417984 ,
        0.07109493, -1.85650592, -0.29961185,  0.7308743 , -1.42876664,
        0.56477951, -0.40785645,  1.06562861, -0.38137242,  0.50583908,
       -0.12103628,  1.19326741,  0.25971743,  1.57767239, -1.35513261,
        0.92033026,  0.47558284,  0.19600111,  0.79835799, -0.21061281,
        0.11150155,  0.35461596,  1.64168828,  0.05395004, -2.59289931,
        0.93523652,  1.28235903,  1.74509119,  0.10755293, -0.22542561,
        0.30216469, -0.13825876, -0.97302133,  0.96868816,  1.61763412,
        0.73260591,  0.38802522, -1.15925801, -0.74192548,  0.16661615,
        1.14764753, -0.22556514, -1.67817643, -1.56003779,  0.78270249,
        0.82195079,  0.07828005, -0.41813434, -0.41187667, -0.24017737,
        1.56311999, -2.56584209,  1.73128247,  1.00093243, -1.06152531,
       -0.28326266,  0.40536332,  0.56056526,  1.69084024,  1.39

# Binomial Distrbution

In [25]:
np.random.binomial(n=1, p=.5, size=1)

array([1])

In [28]:
# repeat experiment
np.random.binomial(n=10, p=.5, size=1)

array([5])

In [30]:
x = np.random.poisson(100, 109)

# Poisson

In [36]:
p = np.random.poisson(100, 10)

In [37]:
p

array([104, 122, 102,  95, 109,  92, 104, 103, 113, 112])

In [38]:
p[p>110]

array([122, 113, 112])